version: "3.7"
services:
  crafty_shop_core_dev:
      build:
        context: .
      working_dir: /app
      env_file:
        - ./config/dev.env
      ports:
        - 3000:3000
      depends_on:
        - postgres
      volumes:
        - ./:/app
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '2345:5432'
    volumes:
      - ~/pg_data/crafty_shop_dev:/var/lib/postgresql/data
    