version: "3.7"
services:
  crafty_shop_core:
      build:
        context: .
        target: production
      command:  "npm run start"
      working_dir: /app
      env_file:
        - ./config/prod.env
      ports:
        - 3000:3000
      depends_on:
        - postgres
      restart: always
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '2345:5432'
    volumes:
      - ~/pg_data/crafty_shop_prod:/var/lib/postgresql/data
    